### ISSUE TITLE
I can haz release tag?

### ISSUE THREAD

**Issue by TravisCarden** [developerforce/Force.com-Toolkit-for-PHP#32]
I notice there are no releases (tags) in the repo, even though some commits make mention of version numbers (e.g., v20.0). As an API consumer, I want to make my application depend on some kind of "latest stable release", but I don't see anything indicating there is such a thing. Is master just supposed to always be stable?

**Comment by maarten00** [comment]
Why is this being ignored? A release tag is crucial for serious developers and takes 1 minute to create. Please create a release tag.

**Comment by metadaddy-sfdc** [comment]
Apologies for the delay in replying here. I don't have a problem with a release tag, but I'm not sure what would make a useful numbering convention. We are currently on version 33.0 of the Force.com APIs, but the PHP toolkit doesn't really target the API version. It seems odd to start at 1.0, since this thing has been around for years.

Any suggestions for what would make a meaningful version number?

**Comment by maarten00** [comment]
It is possible to create release tags on older releases, so you could start adding a 1.0 tag on commit https://github.com/developerforce/Force.com-Toolkit-for-PHP/commit/dfb69d1dde7ff604fe26fe09885ca1ad4b1a64a6 and version a few other commits until you reach the latest version which could be major release 2, 3, 4 etc. It doesn't really matter that much.

Or you could just start with version 1.0, anyone who wants to use an older version is already loading an older untagged version on commit number.

**Comment by metadaddy-sfdc** [comment]
I ended up basing the release numbers on the targeted API version, so the first version to target API v20.0 was release 20.0.0, subsequent iterations incrementing the micro release number until the targeted version changes. I didn't create a tag for every commit, since some days there were multiple commits, and it didn't seem to make much sense to separate them out. Hope this works for you!
